name = "KissABC"
uuid = "9c9dad79-530a-4643-a18b-2704674d4108"
authors = ["Francesco Alemanno <francescoalemanno710@gmail.com>"]
version = "3.0.1"

[deps]
AbstractMCMC = "80f14c24-f653-4e6a-9b94-39d6b0f70001"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
MonteCarloMeasurements = "0987c9cc-fe09-11e8-30f0-b96dd679fdca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
AbstractMCMC = "2.1.0 - 3.0.0"
Distributions = "0.18 - 0.30"
MonteCarloMeasurements = "0.9.5 - 1.0.0"
julia = "1.3 - 2.0"

[extras]
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Statistics", "Test"]
